Let's look into the stats of the bert word embeddings. 

In [1]:
import transformers
import torch

/Users/I745698/miniconda3/envs/p311/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [14]:
CLS = 101
QUERY = 23032
PASSAGE = 6019
COLON = 1024
SEP = 102
PAD = 0



e5 = transformers.AutoModel.from_pretrained("intfloat/e5-small", attn_implementation="eager")
table = e5.embeddings.word_embeddings.weight
table = table

/Users/I745698/miniconda3/envs/p311/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [15]:
table

Parameter containing:
tensor([[ 0.0334,  0.0167,  0.0518,  ...,  0.0848, -0.0148, -0.0687],
        [-0.0720, -0.0928, -0.0335,  ..., -0.0760, -0.0031,  0.0216],
        [-0.0252,  0.0263,  0.0354,  ...,  0.0872, -0.0119,  0.0695],
        ...,
        [-0.0491, -0.0770, -0.0300,  ...,  0.0209, -0.1053, -0.0556],
        [ 0.0435, -0.0742,  0.0164,  ...,  0.1011, -0.0241, -0.0189],
        [ 0.0355, -0.1061,  0.0835,  ..., -0.0921,  0.0757,  0.0495]],
       requires_grad=True)

In [16]:
table.mean(dim=-1)



tensor([ 0.0028, -0.0003, -0.0007,  ..., -0.0004, -0.0001, -0.0006],
       grad_fn=<MeanBackward1>)

In [17]:
table.abs().mean()

tensor(0.0949, grad_fn=<MeanBackward0>)

In [18]:
torch.std_mean(table, dim=-1)

(tensor([0.1422, 0.0825, 0.0779,  ..., 0.0782, 0.0778, 0.0947],
        grad_fn=<StdMeanBackward0>),
 tensor([ 0.0028, -0.0003, -0.0007,  ..., -0.0004, -0.0001, -0.0006],
        grad_fn=<StdMeanBackward0>))

In [19]:
torch.std(table, dim=-1).mean()

# This is the right scaling factor. 

tensor(0.1192, grad_fn=<MeanBackward0>)

In [20]:
print(torch.std(table, dim=-1).min(), torch.std(table, dim=-1).max())

# If the std falls outside this range. 

tensor(0.0188, grad_fn=<MinBackward1>) tensor(0.1682, grad_fn=<MaxBackward1>)


In [21]:
table.std(-1).numel()

30522

In [9]:
table.abs().max(dim=-1)

torch.return_types.max(
values=tensor([0.3499, 0.5342, 0.4802, 0.7554, 0.7642, 0.4082],
       grad_fn=<MaxBackward0>),
indices=tensor([139,   3, 301,   3, 323, 312]))